package com.spn.common

object Constants {
  val RESP_INITIAL_CONFIG = "RESP_INITIAL_CONFIG"
  val RESP_MENU = "RESP_MENU"
  val RESP_RANDOM_PAGE_URL = "RANDOM_PAGE_URL"
  val RESP_AUTH_TOKEN = "RESP_AUTH_TOKEN"
  val RESP_AUTH_TOKEN_DUMMY_VAL = "RESP_AUTH_TOKEN_DUMMY_VAL"
  val RESP_ACTIVATION_CODE= "activationCode"
  val RESP_ACTIVATION_CODE_DUMMY_VAL = "RESP_ACTIVATION_TOKEN_DUMMY_VAL"
  val RESP_SECURITY_TOKEN= "RESP_SECURITY_TOKEN"
  val RESP_SECURITY_TOKEN_DUMMY_VAL = "RESP_SECURITY_TOKEN_DUMMY_VAL"
  val RESP_DEVICE_SERIAL_NUMBER = "RESP_DEVICE_SERIAL_NUMBER"
  var RESP_PAGE_RESPONSE = "RESP_PAGE_RESPONSE"
  var RESP_COUNT_OF_ITEMS_IN_PAGE = "RESP_COUNT_OF_ITEMS_IN_PAGE"
  var RESP_TRAY_SEARCH_VOD_RESPONSE = "RESP_TRAY_SEARCH_VOD_RESPONSE"
  var RESP_TRAY_SEARCH_RESPONSE = "RESP_TRAY_SEARCH_RESPONSE"
  var RESP_CONTENT_ID = "contentId"
  var RESP_GET_MY_LIST = "RESP_GET_MY_LIST"
  val RESP_EPG_RESPONSE = "RESP_EPG_RESPONSE"
  val RESP_GENERIC_COUPON ="RESP_GENERIC_COUPON"

  // Type of Users
  val REQ_USER_TYPE = "userType"
  val USER_TYPE_GUEST = "GUEST"
  val USER_TYPE_LOGGED_IN = "LOGGED_IN"

}

