package com.spn.common

object Constants {
  val RESP_INITIAL_CONFIG = "RESP_INITIAL_CONFIG"
  val RESP_MENU = "RESP_MENU"
  val RESP_RANDOM_PAGE_URL = "RANDOM_PAGE_URL"
  val RESP_AUTH_TOKEN = "RESP_AUTH_TOKEN"
  val RESP_ACTIVATION_CODE= "RESP_ACTIVATION_CODE"
  val RESP_SECURITY_TOKEN= "RESP_SECURITY_TOKEN"
  val RESP_SECURITY_TOKEN_DUMMY_VAL = "RESP_SECURITY_TOKEN_DUMMY_VAL"
  val RESP_DEVICE_SERIAL_NUMBER = "RESP_DEVICE_SERIAL_NUMBER"

  // Type of Users
  val REQ_USER_TYPE = "userType"
  val USER_TYPE_GUEST = "GUEST"
  val USER_TYPE_LOGGED_IN = "LOGGED_IN"

}

