package com.spn.common

object Constants {
  val RESP_INITIAL_CONFIG = "RESP_INITIAL_CONFIG"
  val RESP_MENU = "RESP_MENU"
  val RESP_RANDOM_PAGE_URL = "RANDOM_PAGE_URL"
  val RESP_AUTH_TOKEN = "RESP_AUTH_TOKEN"
  val RESP_ACTIVATION_CODE= "RESP_ACTIVATION_CODE"
}
